from project_integration.generate_blank_lines import add_blank_lines
from project_integration.handle_user_input.get_user_inputs import get_user_inputs
from project_integration.handle_user_input.get_user_inputs import write_user_inputs_to_csv
from project_integration.handle_user_input.user_input_mapping import user_input_mapping
from project_integration.handle_user_input.generate_risk_score_display import get_input_for_risk_score, display_risk_score, display_risk_suggestion
from project_integration.recommendation_controller.controller import controller