from recommendation_tool.risk_assessment.risk_predictor import risk_predict
from recommendation_tool.risk_assessment.is_obese import is_obese
from recommendation_tool.physical_activity_recommendation.physical_activity_recommend import calculate_calorie_burn